"""
ThunderCat6 Constants
"""

# FTDI Configuration
FTDI_VID = 0x0403
FTDI_PID = 0x6011  # FT4232H
DEFAULT_BAUDRATE = 115200

# I2C Addresses (7-bit)
I2C_ADDR_BR = 0x20      # Barlow Ridge
I2C_ADDR_KR = 0x21      # Kaby Ridge
I2C_ADDR_PD1 = 0x08     # PD Controller 1 (PMG1-S3)
I2C_ADDR_PD2 = 0x09     # PD Controller 2 (PMG1-S3)
I2C_ADDR_FX20 = 0x30    # FX20 USB Traffic Generator
I2C_ADDR_MST = 0x28     # MST Hub (Realtek)
I2C_ADDR_USB_HUB = 0x2C # USB2 Hub
I2C_ADDR_HS_MUX = 0x70  # High-Speed Mux

# GPIO Pin Assignments (FTDI)
GPIO_BR_RESET = 0
GPIO_KR_RESET = 1
GPIO_FX20_RESET = 2
GPIO_MST_RESET = 3
GPIO_HPD_CTRL = 4
GPIO_HS_MUX_SEL0 = 5
GPIO_HS_MUX_SEL1 = 6
GPIO_LED_ERR = 7

# DIP Switch
DIP_SWITCH_BITS = 4
DIP_SWITCH_MAX = 15

# Timeouts (seconds)
TIMEOUT_MODE_SWITCH = 7.0
TIMEOUT_MODE_SWITCH_FAST = 0.5
TIMEOUT_RESET = 2.0
TIMEOUT_CONNECT = 5.0

# Error Codes
ERR_SUCCESS = 0x00
ERR_TIMEOUT = 0x01
ERR_INVALID_MODE = 0x02
ERR_COMMUNICATION = 0x03
ERR_DEVICE_NOT_READY = 0x04
ERR_INVALID_PARAMETER = 0x05

# Status Flags
STATUS_BR_LINK_UP = 0x01
STATUS_KR_LINK_UP = 0x02
STATUS_USB_CONNECTED = 0x04
STATUS_DP_CONNECTED = 0x08
STATUS_PCIE_CONNECTED = 0x10
STATUS_ERROR = 0x80

# Component IDs
COMPONENT_BR = "br"
COMPONENT_KR = "kr"
COMPONENT_PD = "pd"
COMPONENT_FTDI = "ftdi"
COMPONENT_FX20 = "fx20"
COMPONENT_MST = "mst"
COMPONENT_USB_HUB = "usb_hub"
COMPONENT_ALL = "all"
